// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe3IoJZnrY-sUNV4jTyEYfTUpM-whYJi8',
    appId: '1:538109518725:android:e4b4324f665e4dd2ed5aec',
    messagingSenderId: '538109518725',
    projectId: 'sienapa-734e9',
    databaseURL: 'https://sienapa-734e9-default-rtdb.firebaseio.com',
    storageBucket: 'sienapa-734e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE2ktYvoAobfm6yvfLZu3srVGJ7wN5-UU',
    appId: '1:538109518725:ios:026ce5a379b46459ed5aec',
    messagingSenderId: '538109518725',
    projectId: 'sienapa-734e9',
    databaseURL: 'https://sienapa-734e9-default-rtdb.firebaseio.com',
    storageBucket: 'sienapa-734e9.appspot.com',
    iosClientId: '538109518725-kis5a6pmoksq5iv1pu61duq1lef3rusu.apps.googleusercontent.com',
    iosBundleId: 'com.example.sienapaMovil',
  );
}
